package sink.com

import org.apache.flink.streaming.api.scala.StreamExecutionEnvironment
import org.apache.flink.table.api.bridge.scala.StreamTableEnvironment

object Source {
  def main(args: Array[String]): Unit = {
  }

  def source_mysql0 : String  =  {
    val mysql_sources0  =
      """
        |CREATE TABLE t_patents_new_0 (
        |id bigint ,
        |outhor_num string ,
        |outhor_date string ,
        |authorize_num string ,
        |authorize_date string ,
        |patent_name string ,
        |request_num string ,
        |request_num_standard string,
        |request_date string ,
        |outhor_change_pub_date string ,
        |outhor_change_pub_no string ,
        |authorize_change_pub_date string ,
        |authorize_change_pub_no string ,
        |decrypt_pub_date string ,
        |type string ,
        |type_name string ,
        |authorize_tag string ,
        |category_num_ipc string ,
        |brief string ,
        |patent_person_ori string,
        |patent_person string ,
        |app_person string ,
        |designer string ,
        |agent_people string ,
        |agent string,
        |agent_info_eid string ,
        |pct_req_data string ,
        |pct_pub_data string ,
        |pct_date string ,
        |priority string ,
        |priority_local string ,
        |qrcode string ,
        |address string ,
        |zipcode string ,
        |status string ,
        |last_status string,
        |compare_files string,
        |patent_img string ,
        |org_patent_img string ,
        |annex string ,
        |related_companies string ,
        |source string ,
        |url string ,
        |u_tags bigint ,
        |is_history bigint ,
        |create_time bigint ,
        |row_update_time string ,
        |PRIMARY KEY(request_num_standard) NOT ENFORCED
        |) WITH (
        | 'connector' = 'mysql-cdc',
        | 'hostname' = '10.255.65.84',
        | 'port' = '3306',
        | 'username' = 'app',
        | 'password' = 'Syx@123456',
        | 'database-name' = 'db_intellectual_property',
        | 'table-name' = 't_patents_new_0',
        | 'scan.incremental.snapshot.enabled' = 'false'
        |)
        |""".stripMargin
    mysql_sources0
  }
  def source_mysql1 : String  =  {
    val mysql_sources1  =
      """
        |CREATE TABLE t_patents_new_1 (
        |id bigint ,
        |outhor_num string ,
        |outhor_date string ,
        |authorize_num string ,
        |authorize_date string ,
        |patent_name string ,
        |request_num string ,
        |request_num_standard string,
        |request_date string ,
        |outhor_change_pub_date string ,
        |outhor_change_pub_no string ,
        |authorize_change_pub_date string ,
        |authorize_change_pub_no string ,
        |decrypt_pub_date string ,
        |type string ,
        |type_name string ,
        |authorize_tag string ,
        |category_num_ipc string ,
        |brief string ,
        |patent_person_ori string,
        |patent_person string ,
        |app_person string ,
        |designer string ,
        |agent_people string ,
        |agent string,
        |agent_info_eid string ,
        |pct_req_data string ,
        |pct_pub_data string ,
        |pct_date string ,
        |priority string ,
        |priority_local string ,
        |qrcode string ,
        |address string ,
        |zipcode string ,
        |status string ,
        |last_status string,
        |compare_files string,
        |patent_img string ,
        |org_patent_img string ,
        |annex string ,
        |related_companies string ,
        |source string ,
        |url string ,
        |u_tags bigint ,
        |is_history bigint ,
        |create_time bigint ,
        |row_update_time string ,
        |PRIMARY KEY(request_num_standard) NOT ENFORCED
        |) WITH (
        | 'connector' = 'mysql-cdc',
        | 'hostname' = '10.255.65.84',
        | 'port' = '3306',
        | 'username' = 'app',
        | 'password' = 'Syx@123456',
        | 'database-name' = 'db_intellectual_property',
        | 'table-name' = 't_patents_new_1',
        | 'scan.incremental.snapshot.enabled' = 'false'
        |)
        |""".stripMargin
    mysql_sources1
  }
  def source_mysql2 : String  =  {
    val mysql_sources2  =
      """
        |CREATE TABLE t_patents_new_2 (
        |id bigint ,
        |outhor_num string ,
        |outhor_date string ,
        |authorize_num string ,
        |authorize_date string ,
        |patent_name string ,
        |request_num string ,
        |request_num_standard string,
        |request_date string ,
        |outhor_change_pub_date string ,
        |outhor_change_pub_no string ,
        |authorize_change_pub_date string ,
        |authorize_change_pub_no string ,
        |decrypt_pub_date string ,
        |type string ,
        |type_name string ,
        |authorize_tag string ,
        |category_num_ipc string ,
        |brief string ,
        |patent_person_ori string,
        |patent_person string ,
        |app_person string ,
        |designer string ,
        |agent_people string ,
        |agent string,
        |agent_info_eid string ,
        |pct_req_data string ,
        |pct_pub_data string ,
        |pct_date string ,
        |priority string ,
        |priority_local string ,
        |qrcode string ,
        |address string ,
        |zipcode string ,
        |status string ,
        |last_status string,
        |compare_files string,
        |patent_img string ,
        |org_patent_img string ,
        |annex string ,
        |related_companies string ,
        |source string ,
        |url string ,
        |u_tags bigint ,
        |is_history bigint ,
        |create_time bigint ,
        |row_update_time string ,
        |PRIMARY KEY(request_num_standard) NOT ENFORCED
        |) WITH (
        | 'connector' = 'mysql-cdc',
        | 'hostname' = '10.255.65.84',
        | 'port' = '3306',
        | 'username' = 'app',
        | 'password' = 'Syx@123456',
        | 'database-name' = 'db_intellectual_property',
        | 'table-name' = 't_patents_new_2',
        | 'scan.incremental.snapshot.enabled' = 'false'
        |)
        |""".stripMargin
    mysql_sources2
  }
  def source_mysql3 : String  =  {
    val mysql_sources3  =
      """
        |CREATE TABLE t_patents_new_3 (
        |id bigint ,
        |outhor_num string ,
        |outhor_date string ,
        |authorize_num string ,
        |authorize_date string ,
        |patent_name string ,
        |request_num string ,
        |request_num_standard string,
        |request_date string ,
        |outhor_change_pub_date string ,
        |outhor_change_pub_no string ,
        |authorize_change_pub_date string ,
        |authorize_change_pub_no string ,
        |decrypt_pub_date string ,
        |type string ,
        |type_name string ,
        |authorize_tag string ,
        |category_num_ipc string ,
        |brief string ,
        |patent_person_ori string,
        |patent_person string ,
        |app_person string ,
        |designer string ,
        |agent_people string ,
        |agent string,
        |agent_info_eid string ,
        |pct_req_data string ,
        |pct_pub_data string ,
        |pct_date string ,
        |priority string ,
        |priority_local string ,
        |qrcode string ,
        |address string ,
        |zipcode string ,
        |status string ,
        |last_status string,
        |compare_files string,
        |patent_img string ,
        |org_patent_img string ,
        |annex string ,
        |related_companies string ,
        |source string ,
        |url string ,
        |u_tags bigint ,
        |is_history bigint ,
        |create_time bigint ,
        |row_update_time string ,
        |PRIMARY KEY(request_num_standard) NOT ENFORCED
        |) WITH (
        | 'connector' = 'mysql-cdc',
        | 'hostname' = '10.255.65.84',
        | 'port' = '3306',
        | 'username' = 'app',
        | 'password' = 'Syx@123456',
        | 'database-name' = 'db_intellectual_property',
        | 'table-name' = 't_patents_new_3',
        | 'scan.incremental.snapshot.enabled' = 'false'
        |)
        |""".stripMargin
    mysql_sources3
  }
  def source_mysql4 : String  =  {
    val mysql_sources4  =
      """
        |CREATE TABLE t_patents_new_4 (
        |id bigint ,
        |outhor_num string ,
        |outhor_date string ,
        |authorize_num string ,
        |authorize_date string ,
        |patent_name string ,
        |request_num string ,
        |request_num_standard string,
        |request_date string ,
        |outhor_change_pub_date string ,
        |outhor_change_pub_no string ,
        |authorize_change_pub_date string ,
        |authorize_change_pub_no string ,
        |decrypt_pub_date string ,
        |type string ,
        |type_name string ,
        |authorize_tag string ,
        |category_num_ipc string ,
        |brief string ,
        |patent_person_ori string,
        |patent_person string ,
        |app_person string ,
        |designer string ,
        |agent_people string ,
        |agent string,
        |agent_info_eid string ,
        |pct_req_data string ,
        |pct_pub_data string ,
        |pct_date string ,
        |priority string ,
        |priority_local string ,
        |qrcode string ,
        |address string ,
        |zipcode string ,
        |status string ,
        |last_status string,
        |compare_files string,
        |patent_img string ,
        |org_patent_img string ,
        |annex string ,
        |related_companies string ,
        |source string ,
        |url string ,
        |u_tags bigint ,
        |is_history bigint ,
        |create_time bigint ,
        |row_update_time string ,
        |PRIMARY KEY(request_num_standard) NOT ENFORCED
        |) WITH (
        | 'connector' = 'mysql-cdc',
        | 'hostname' = '10.255.65.84',
        | 'port' = '3306',
        | 'username' = 'app',
        | 'password' = 'Syx@123456',
        | 'database-name' = 'db_intellectual_property',
        | 'table-name' = 't_patents_new_4',
        | 'scan.incremental.snapshot.enabled' = 'false'
        |)
        |""".stripMargin
    mysql_sources4
  }
  def source_mysql5 : String  =  {
    val mysql_sources5  =
      """
        |CREATE TABLE t_patents_new_5 (
        |id bigint ,
        |outhor_num string ,
        |outhor_date string ,
        |authorize_num string ,
        |authorize_date string ,
        |patent_name string ,
        |request_num string ,
        |request_num_standard string,
        |request_date string ,
        |outhor_change_pub_date string ,
        |outhor_change_pub_no string ,
        |authorize_change_pub_date string ,
        |authorize_change_pub_no string ,
        |decrypt_pub_date string ,
        |type string ,
        |type_name string ,
        |authorize_tag string ,
        |category_num_ipc string ,
        |brief string ,
        |patent_person_ori string,
        |patent_person string ,
        |app_person string ,
        |designer string ,
        |agent_people string ,
        |agent string,
        |agent_info_eid string ,
        |pct_req_data string ,
        |pct_pub_data string ,
        |pct_date string ,
        |priority string ,
        |priority_local string ,
        |qrcode string ,
        |address string ,
        |zipcode string ,
        |status string ,
        |last_status string,
        |compare_files string,
        |patent_img string ,
        |org_patent_img string ,
        |annex string ,
        |related_companies string ,
        |source string ,
        |url string ,
        |u_tags bigint ,
        |is_history bigint ,
        |create_time bigint ,
        |row_update_time string ,
        |PRIMARY KEY(request_num_standard) NOT ENFORCED
        |) WITH (
        | 'connector' = 'mysql-cdc',
        | 'hostname' = '10.255.65.84',
        | 'port' = '3306',
        | 'username' = 'app',
        | 'password' = 'Syx@123456',
        | 'database-name' = 'db_intellectual_property',
        | 'table-name' = 't_patents_new_5',
        | 'scan.incremental.snapshot.enabled' = 'false'
        |)
        |""".stripMargin
    mysql_sources5
  }
  def source_mysql6 : String  =  {
    val mysql_sources6  =
      """
        |CREATE TABLE t_patents_new_6 (
        |id bigint ,
        |outhor_num string ,
        |outhor_date string ,
        |authorize_num string ,
        |authorize_date string ,
        |patent_name string ,
        |request_num string ,
        |request_num_standard string,
        |request_date string ,
        |outhor_change_pub_date string ,
        |outhor_change_pub_no string ,
        |authorize_change_pub_date string ,
        |authorize_change_pub_no string ,
        |decrypt_pub_date string ,
        |type string ,
        |type_name string ,
        |authorize_tag string ,
        |category_num_ipc string ,
        |brief string ,
        |patent_person_ori string,
        |patent_person string ,
        |app_person string ,
        |designer string ,
        |agent_people string ,
        |agent string,
        |agent_info_eid string ,
        |pct_req_data string ,
        |pct_pub_data string ,
        |pct_date string ,
        |priority string ,
        |priority_local string ,
        |qrcode string ,
        |address string ,
        |zipcode string ,
        |status string ,
        |last_status string,
        |compare_files string,
        |patent_img string ,
        |org_patent_img string ,
        |annex string ,
        |related_companies string ,
        |source string ,
        |url string ,
        |u_tags bigint ,
        |is_history bigint ,
        |create_time bigint ,
        |row_update_time string ,
        |PRIMARY KEY(request_num_standard) NOT ENFORCED
        |) WITH (
        | 'connector' = 'mysql-cdc',
        | 'hostname' = '10.255.65.84',
        | 'port' = '3306',
        | 'username' = 'app',
        | 'password' = 'Syx@123456',
        | 'database-name' = 'db_intellectual_property',
        | 'table-name' = 't_patents_new_6',
        | 'scan.incremental.snapshot.enabled' = 'false'
        |)
        |""".stripMargin
    mysql_sources6
  }
  def source_mysql7 : String  =  {
    val mysql_sources7  =
      """
        |CREATE TABLE t_patents_new_7 (
        |id bigint ,
        |outhor_num string ,
        |outhor_date string ,
        |authorize_num string ,
        |authorize_date string ,
        |patent_name string ,
        |request_num string ,
        |request_num_standard string,
        |request_date string ,
        |outhor_change_pub_date string ,
        |outhor_change_pub_no string ,
        |authorize_change_pub_date string ,
        |authorize_change_pub_no string ,
        |decrypt_pub_date string ,
        |type string ,
        |type_name string ,
        |authorize_tag string ,
        |category_num_ipc string ,
        |brief string ,
        |patent_person_ori string,
        |patent_person string ,
        |app_person string ,
        |designer string ,
        |agent_people string ,
        |agent string,
        |agent_info_eid string ,
        |pct_req_data string ,
        |pct_pub_data string ,
        |pct_date string ,
        |priority string ,
        |priority_local string ,
        |qrcode string ,
        |address string ,
        |zipcode string ,
        |status string ,
        |last_status string,
        |compare_files string,
        |patent_img string ,
        |org_patent_img string ,
        |annex string ,
        |related_companies string ,
        |source string ,
        |url string ,
        |u_tags bigint ,
        |is_history bigint ,
        |create_time bigint ,
        |row_update_time string ,
        |PRIMARY KEY(request_num_standard) NOT ENFORCED
        |) WITH (
        | 'connector' = 'mysql-cdc',
        | 'hostname' = '10.255.65.84',
        | 'port' = '3306',
        | 'username' = 'app',
        | 'password' = 'Syx@123456',
        | 'database-name' = 'db_intellectual_property',
        | 'table-name' = 't_patents_new_7',
        | 'scan.incremental.snapshot.enabled' = 'false'
        |)
        |""".stripMargin
    mysql_sources7
  }
  def source_mysql8 : String  =  {
    val mysql_sources8  =
      """
        |CREATE TABLE t_patents_new_8 (
        |id bigint ,
        |outhor_num string ,
        |outhor_date string ,
        |authorize_num string ,
        |authorize_date string ,
        |patent_name string ,
        |request_num string ,
        |request_num_standard string,
        |request_date string ,
        |outhor_change_pub_date string ,
        |outhor_change_pub_no string ,
        |authorize_change_pub_date string ,
        |authorize_change_pub_no string ,
        |decrypt_pub_date string ,
        |type string ,
        |type_name string ,
        |authorize_tag string ,
        |category_num_ipc string ,
        |brief string ,
        |patent_person_ori string,
        |patent_person string ,
        |app_person string ,
        |designer string ,
        |agent_people string ,
        |agent string,
        |agent_info_eid string ,
        |pct_req_data string ,
        |pct_pub_data string ,
        |pct_date string ,
        |priority string ,
        |priority_local string ,
        |qrcode string ,
        |address string ,
        |zipcode string ,
        |status string ,
        |last_status string,
        |compare_files string,
        |patent_img string ,
        |org_patent_img string ,
        |annex string ,
        |related_companies string ,
        |source string ,
        |url string ,
        |u_tags bigint ,
        |is_history bigint ,
        |create_time bigint ,
        |row_update_time string ,
        |PRIMARY KEY(request_num_standard) NOT ENFORCED
        |) WITH (
        | 'connector' = 'mysql-cdc',
        | 'hostname' = '10.255.65.84',
        | 'port' = '3306',
        | 'username' = 'app',
        | 'password' = 'Syx@123456',
        | 'database-name' = 'db_intellectual_property',
        | 'table-name' = 't_patents_new_8',
        | 'scan.incremental.snapshot.enabled' = 'false'
        |)
        |""".stripMargin
    mysql_sources8
  }
  def source_mysql9 : String  =  {
    val mysql_sources9  =
      """
        |CREATE TABLE t_patents_new_9 (
        |id bigint ,
        |outhor_num string ,
        |outhor_date string ,
        |authorize_num string ,
        |authorize_date string ,
        |patent_name string ,
        |request_num string ,
        |request_num_standard string,
        |request_date string ,
        |outhor_change_pub_date string ,
        |outhor_change_pub_no string ,
        |authorize_change_pub_date string ,
        |authorize_change_pub_no string ,
        |decrypt_pub_date string ,
        |type string ,
        |type_name string ,
        |authorize_tag string ,
        |category_num_ipc string ,
        |brief string ,
        |patent_person_ori string,
        |patent_person string ,
        |app_person string ,
        |designer string ,
        |agent_people string ,
        |agent string,
        |agent_info_eid string ,
        |pct_req_data string ,
        |pct_pub_data string ,
        |pct_date string ,
        |priority string ,
        |priority_local string ,
        |qrcode string ,
        |address string ,
        |zipcode string ,
        |status string ,
        |last_status string,
        |compare_files string,
        |patent_img string ,
        |org_patent_img string ,
        |annex string ,
        |related_companies string ,
        |source string ,
        |url string ,
        |u_tags bigint ,
        |is_history bigint ,
        |create_time bigint ,
        |row_update_time string ,
        |PRIMARY KEY(request_num_standard) NOT ENFORCED
        |) WITH (
        | 'connector' = 'mysql-cdc',
        | 'hostname' = '10.255.65.84',
        | 'port' = '3306',
        | 'username' = 'app',
        | 'password' = 'Syx@123456',
        | 'database-name' = 'db_intellectual_property',
        | 'table-name' = 't_patents_new_9',
        | 'scan.incremental.snapshot.enabled' = 'false'
        |)
        |""".stripMargin
    mysql_sources9
  }
  def source_mysql10 : String  =  {
    val mysql_sources10  =
      """
        |CREATE TABLE t_patents_new_10 (
        |id bigint ,
        |outhor_num string ,
        |outhor_date string ,
        |authorize_num string ,
        |authorize_date string ,
        |patent_name string ,
        |request_num string ,
        |request_num_standard string,
        |request_date string ,
        |outhor_change_pub_date string ,
        |outhor_change_pub_no string ,
        |authorize_change_pub_date string ,
        |authorize_change_pub_no string ,
        |decrypt_pub_date string ,
        |type string ,
        |type_name string ,
        |authorize_tag string ,
        |category_num_ipc string ,
        |brief string ,
        |patent_person_ori string,
        |patent_person string ,
        |app_person string ,
        |designer string ,
        |agent_people string ,
        |agent string,
        |agent_info_eid string ,
        |pct_req_data string ,
        |pct_pub_data string ,
        |pct_date string ,
        |priority string ,
        |priority_local string ,
        |qrcode string ,
        |address string ,
        |zipcode string ,
        |status string ,
        |last_status string,
        |compare_files string,
        |patent_img string ,
        |org_patent_img string ,
        |annex string ,
        |related_companies string ,
        |source string ,
        |url string ,
        |u_tags bigint ,
        |is_history bigint ,
        |create_time bigint ,
        |row_update_time string ,
        |PRIMARY KEY(request_num_standard) NOT ENFORCED
        |) WITH (
        | 'connector' = 'mysql-cdc',
        | 'hostname' = '10.255.65.84',
        | 'port' = '3306',
        | 'username' = 'app',
        | 'password' = 'Syx@123456',
        | 'database-name' = 'db_intellectual_property',
        | 'table-name' = 't_patents_new_10',
        | 'scan.incremental.snapshot.enabled' = 'false'
        |)
        |""".stripMargin
    mysql_sources10
  }
  def source_mysql11 : String  =  {
    val mysql_sources11  =
      """
        |CREATE TABLE t_patents_new_11 (
        |id bigint ,
        |outhor_num string ,
        |outhor_date string ,
        |authorize_num string ,
        |authorize_date string ,
        |patent_name string ,
        |request_num string ,
        |request_num_standard string,
        |request_date string ,
        |outhor_change_pub_date string ,
        |outhor_change_pub_no string ,
        |authorize_change_pub_date string ,
        |authorize_change_pub_no string ,
        |decrypt_pub_date string ,
        |type string ,
        |type_name string ,
        |authorize_tag string ,
        |category_num_ipc string ,
        |brief string ,
        |patent_person_ori string,
        |patent_person string ,
        |app_person string ,
        |designer string ,
        |agent_people string ,
        |agent string,
        |agent_info_eid string ,
        |pct_req_data string ,
        |pct_pub_data string ,
        |pct_date string ,
        |priority string ,
        |priority_local string ,
        |qrcode string ,
        |address string ,
        |zipcode string ,
        |status string ,
        |last_status string,
        |compare_files string,
        |patent_img string ,
        |org_patent_img string ,
        |annex string ,
        |related_companies string ,
        |source string ,
        |url string ,
        |u_tags bigint ,
        |is_history bigint ,
        |create_time bigint ,
        |row_update_time string ,
        |PRIMARY KEY(request_num_standard) NOT ENFORCED
        |) WITH (
        | 'connector' = 'mysql-cdc',
        | 'hostname' = '10.255.65.84',
        | 'port' = '3306',
        | 'username' = 'app',
        | 'password' = 'Syx@123456',
        | 'database-name' = 'db_intellectual_property',
        | 'table-name' = 't_patents_new_11',
        | 'scan.incremental.snapshot.enabled' = 'false'
        |)
        |""".stripMargin
    mysql_sources11
  }
  def source_mysql12 : String  =  {
    val mysql_sources12  =
      """
        |CREATE TABLE t_patents_new_12 (
        |id bigint ,
        |outhor_num string ,
        |outhor_date string ,
        |authorize_num string ,
        |authorize_date string ,
        |patent_name string ,
        |request_num string ,
        |request_num_standard string,
        |request_date string ,
        |outhor_change_pub_date string ,
        |outhor_change_pub_no string ,
        |authorize_change_pub_date string ,
        |authorize_change_pub_no string ,
        |decrypt_pub_date string ,
        |type string ,
        |type_name string ,
        |authorize_tag string ,
        |category_num_ipc string ,
        |brief string ,
        |patent_person_ori string,
        |patent_person string ,
        |app_person string ,
        |designer string ,
        |agent_people string ,
        |agent string,
        |agent_info_eid string ,
        |pct_req_data string ,
        |pct_pub_data string ,
        |pct_date string ,
        |priority string ,
        |priority_local string ,
        |qrcode string ,
        |address string ,
        |zipcode string ,
        |status string ,
        |last_status string,
        |compare_files string,
        |patent_img string ,
        |org_patent_img string ,
        |annex string ,
        |related_companies string ,
        |source string ,
        |url string ,
        |u_tags bigint ,
        |is_history bigint ,
        |create_time bigint ,
        |row_update_time string ,
        |PRIMARY KEY(request_num_standard) NOT ENFORCED
        |) WITH (
        | 'connector' = 'mysql-cdc',
        | 'hostname' = '10.255.65.84',
        | 'port' = '3306',
        | 'username' = 'app',
        | 'password' = 'Syx@123456',
        | 'database-name' = 'db_intellectual_property',
        | 'table-name' = 't_patents_new_12',
        | 'scan.incremental.snapshot.enabled' = 'false'
        |)
        |""".stripMargin
    mysql_sources12
  }
  def source_mysql13 : String  =  {
    val mysql_sources13  =
      """
        |CREATE TABLE t_patents_new_13 (
        |id bigint ,
        |outhor_num string ,
        |outhor_date string ,
        |authorize_num string ,
        |authorize_date string ,
        |patent_name string ,
        |request_num string ,
        |request_num_standard string,
        |request_date string ,
        |outhor_change_pub_date string ,
        |outhor_change_pub_no string ,
        |authorize_change_pub_date string ,
        |authorize_change_pub_no string ,
        |decrypt_pub_date string ,
        |type string ,
        |type_name string ,
        |authorize_tag string ,
        |category_num_ipc string ,
        |brief string ,
        |patent_person_ori string,
        |patent_person string ,
        |app_person string ,
        |designer string ,
        |agent_people string ,
        |agent string,
        |agent_info_eid string ,
        |pct_req_data string ,
        |pct_pub_data string ,
        |pct_date string ,
        |priority string ,
        |priority_local string ,
        |qrcode string ,
        |address string ,
        |zipcode string ,
        |status string ,
        |last_status string,
        |compare_files string,
        |patent_img string ,
        |org_patent_img string ,
        |annex string ,
        |related_companies string ,
        |source string ,
        |url string ,
        |u_tags bigint ,
        |is_history bigint ,
        |create_time bigint ,
        |row_update_time string ,
        |PRIMARY KEY(request_num_standard) NOT ENFORCED
        |) WITH (
        | 'connector' = 'mysql-cdc',
        | 'hostname' = '10.255.65.84',
        | 'port' = '3306',
        | 'username' = 'app',
        | 'password' = 'Syx@123456',
        | 'database-name' = 'db_intellectual_property',
        | 'table-name' = 't_patents_new_13',
        | 'scan.incremental.snapshot.enabled' = 'false'
        |)
        |""".stripMargin
    mysql_sources13
  }
  def source_mysql14 : String  =  {
    val mysql_sources14  =
      """
        |CREATE TABLE t_patents_new_14 (
        |id bigint ,
        |outhor_num string ,
        |outhor_date string ,
        |authorize_num string ,
        |authorize_date string ,
        |patent_name string ,
        |request_num string ,
        |request_num_standard string,
        |request_date string ,
        |outhor_change_pub_date string ,
        |outhor_change_pub_no string ,
        |authorize_change_pub_date string ,
        |authorize_change_pub_no string ,
        |decrypt_pub_date string ,
        |type string ,
        |type_name string ,
        |authorize_tag string ,
        |category_num_ipc string ,
        |brief string ,
        |patent_person_ori string,
        |patent_person string ,
        |app_person string ,
        |designer string ,
        |agent_people string ,
        |agent string,
        |agent_info_eid string ,
        |pct_req_data string ,
        |pct_pub_data string ,
        |pct_date string ,
        |priority string ,
        |priority_local string ,
        |qrcode string ,
        |address string ,
        |zipcode string ,
        |status string ,
        |last_status string,
        |compare_files string,
        |patent_img string ,
        |org_patent_img string ,
        |annex string ,
        |related_companies string ,
        |source string ,
        |url string ,
        |u_tags bigint ,
        |is_history bigint ,
        |create_time bigint ,
        |row_update_time string ,
        |PRIMARY KEY(request_num_standard) NOT ENFORCED
        |) WITH (
        | 'connector' = 'mysql-cdc',
        | 'hostname' = '10.255.65.84',
        | 'port' = '3306',
        | 'username' = 'app',
        | 'password' = 'Syx@123456',
        | 'database-name' = 'db_intellectual_property',
        | 'table-name' = 't_patents_new_14',
        | 'scan.incremental.snapshot.enabled' = 'false'
        |)
        |""".stripMargin
    mysql_sources14
  }
  def source_mysql15 : String  =  {
    val mysql_sources15  =
      """
        |CREATE TABLE t_patents_new_15 (
        |id bigint ,
        |outhor_num string ,
        |outhor_date string ,
        |authorize_num string ,
        |authorize_date string ,
        |patent_name string ,
        |request_num string ,
        |request_num_standard string,
        |request_date string ,
        |outhor_change_pub_date string ,
        |outhor_change_pub_no string ,
        |authorize_change_pub_date string ,
        |authorize_change_pub_no string ,
        |decrypt_pub_date string ,
        |type string ,
        |type_name string ,
        |authorize_tag string ,
        |category_num_ipc string ,
        |brief string ,
        |patent_person_ori string,
        |patent_person string ,
        |app_person string ,
        |designer string ,
        |agent_people string ,
        |agent string,
        |agent_info_eid string ,
        |pct_req_data string ,
        |pct_pub_data string ,
        |pct_date string ,
        |priority string ,
        |priority_local string ,
        |qrcode string ,
        |address string ,
        |zipcode string ,
        |status string ,
        |last_status string,
        |compare_files string,
        |patent_img string ,
        |org_patent_img string ,
        |annex string ,
        |related_companies string ,
        |source string ,
        |url string ,
        |u_tags bigint ,
        |is_history bigint ,
        |create_time bigint ,
        |row_update_time string ,
        |PRIMARY KEY(request_num_standard) NOT ENFORCED
        |) WITH (
        | 'connector' = 'mysql-cdc',
        | 'hostname' = '10.255.65.84',
        | 'port' = '3306',
        | 'username' = 'app',
        | 'password' = 'Syx@123456',
        | 'database-name' = 'db_intellectual_property',
        | 'table-name' = 't_patents_new_15',
        | 'scan.incremental.snapshot.enabled' = 'false'
        |)
        |""".stripMargin
    mysql_sources15
  }






}
